### ISSUE TITLE
[Fix] 2차 오픈 후 수정

### ISSUE THREAD

**Issue by seonyoung42** [YAPP-Github/21st-iOS-Team-1-iOS#103]
## Description
2차 업데이트 후 수정사항

## Todo
- [x] 약관 url 변경
- [x] 개인정보 방침 url 변경
- [x] 동네 카드 주소 텍스트 수정 (00시 00구 00동 -> 00시 00구)
