### ISSUE TITLE
[Common] 폴더 분리

### ISSUE THREAD

**Issue by ungchun** [YAPP-Github/21st-iOS-Team-1-iOS#2]
## Description  
클린 아키텍처 기반 폴더 분리

## Todo
- [x] Data 폴더 추가
- [x] Presentation 폴더 추가
- [x] Domain 폴더 추가
- [x] Application 폴더 추가
- [x] Resource 폴더 추가
- [x] Assets, Info, LaunchScreen 파일 Resource 폴더로 이동
- [x] App Delegate, Scene Delegate Application 폴더로 이동
- [x] ViewController Common View로 이동
- [x] Main StoryBoard 삭제
- [x] CoreData 삭제
