### ISSUE TITLE
[Sign] 시작 화면 UI 구현 

### ISSUE THREAD

**Issue by llghdud921** [YAPP-Github/21st-iOS-Team-1-iOS#59]
## Description 
시작 화면 로고 및 UI 작업 마무리

## Todo
- [x] 시작화면 로고 적용
- [x] 네트워크 실패 시 popup 알림 적용
- [x] tool tip 적용
