### ISSUE TITLE
[Favorite] 찜 화면 네트워크 연결

### ISSUE THREAD

**Issue by seonyoung42** [YAPP-Github/21st-iOS-Team-1-iOS#75]
## Todo
- [x] 찜 화면 API 연결
- [x] UserDefaults 관리 구현
     - [x] isAnonymous UserDefaults로 추가
