### ISSUE TITLE
[Common] UI, Core, Network Package 추가 

### ISSUE THREAD

**Issue by llghdud921** [YAPP-Github/21st-iOS-Team-1-iOS#8]
## Description
UI, Core, Network Package 

## Todo
- [x] FindTownUI package 추가
- [x] FindTownCore package 추가
- [x] FindTownNetwork package 추가
- [x] project 내 target Embedded content에 package 추가
- [x] package 내 platform target 추가

---

### package 내 platform target 추가
package.swift 내 아래 코드 추가
```swift
platforms: [
        .iOS(.v15)
    ],
```
